version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
      RAILS_ENV: test
      RUN_TYPE: 'docker'
    links:
      - db
    ports:
      - 3000:3000

  db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
    ports:
      - 3002:5432
