default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: localhost

development:
  <<: *default
  database: paystats_dev

test: &test
  <<: *default
  database: paystats_test

cucumber:
  <<: *test

production:
  <<: *default
  database: paystats_production
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>