default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: paystats_dev

test: &test
  <<: *default
  database: paystats_test

cucumber:
  <<: *test

production:
  <<: *default
  database: paystats_production
